/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ys507.battleship;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.ResourceAccessMode;
import org.junit.jupiter.api.parallel.ResourceLock;
import org.junit.jupiter.api.parallel.Resources;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.*;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.StringReader;

class AppTest {

    @ParameterizedTest
    @ValueSource(strings = { "2" })
    @ResourceLock(value = Resources.SYSTEM_OUT, mode =
    ResourceAccessMode.READ_WRITE)
    void test_main(String id) throws IOException {
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    PrintStream out = new PrintStream(bytes, true);
    InputStream input = getClass().getClassLoader().getResourceAsStream("input" +
    id + ".txt");
    assertNotNull(input);
    InputStream expectedStream =
    getClass().getClassLoader().getResourceAsStream("output" + id + ".txt");
    assertNotNull(expectedStream);
    InputStream oldIn = System.in;
    PrintStream oldOut = System.out;
    try {
    System.setIn(input);
    System.setOut(out);
    App.main(new String[0]);
    } finally {
    System.setIn(oldIn);
    System.setOut(oldOut);
    }

    String expected = new String(expectedStream.readAllBytes());
    String actual = bytes.toString();
    assertEquals(expected, actual);
    }

    /**
     * Fire at all coordinates of the ship to make it sink
     * 
     * @param <T>
     * @param b    is the board.
     * @param ship the ship to fire at.
     */
    public <T> void addAndSink(Board<T> b, Ship<T> ship) {
        b.tryAddShip(ship);
        for (Coordinate c : ship.getCoordinates()) {
            b.fireAt(c);
        }
    }

    @Test
    public void test_A_win_v1() {
        V1ShipFactory f = new V1ShipFactory();

        BattleShipBoard<Character> boardA = new BattleShipBoard<>(5, 5, 'X');
        BattleShipBoard<Character> boardB = new BattleShipBoard<>(5, 5, 'X');
        BoardTextView viewA = new BoardTextView(boardA);
        BoardTextView viewB = new BoardTextView(boardB);

        Ship<Character> bShip = f.makeSubmarine(new Placement("A0h"));
        addAndSink(boardB, bShip);
        BufferedReader inA = new BufferedReader(new StringReader("A0\n"));
        BufferedReader inB = new BufferedReader(new StringReader("A0\n"));
        ByteArrayOutputStream bytesA = new ByteArrayOutputStream();
        PrintStream outA = new PrintStream(bytesA);
        ByteArrayOutputStream bytesB = new ByteArrayOutputStream();
        PrintStream outB = new PrintStream(bytesB);
        TextPlayer p1 = new TextPlayer(boardA, inA, outA, "A", f);
        TextPlayer p2 = new TextPlayer(boardB, inB, outB, "B", f);

        App app = new App(p1, p2);
        assertDoesNotThrow(() -> app.doAttackPhase());
        assertTrue(boardB.checkForLose());
    }

    @Test
    public void test_B_win_v1() {
        V1ShipFactory f = new V1ShipFactory();

        BattleShipBoard<Character> boardA = new BattleShipBoard<>(5, 5, 'X');
        BattleShipBoard<Character> boardB = new BattleShipBoard<>(5, 5, 'X');

        boardA.tryAddShip(f.makeSubmarine(new Placement("A0h")));
        boardB.tryAddShip(f.makeBattleship(new Placement("A1v")));
        BufferedReader inA = new BufferedReader(new StringReader("A0\nB2\n"));
        BufferedReader inB = new BufferedReader(new StringReader("A0\nA1\n"));
        ByteArrayOutputStream bytesA = new ByteArrayOutputStream();
        PrintStream outA = new PrintStream(bytesA);
        ByteArrayOutputStream bytesB = new ByteArrayOutputStream();
        PrintStream outB = new PrintStream(bytesB);
        TextPlayer p1 = new TextPlayer(boardA, inA, outA, "A", f);
        TextPlayer p2 = new TextPlayer(boardB, inB, outB, "B", f);

        App app = new App(p1, p2);
        assertDoesNotThrow(() -> app.doAttackPhase());
        assertTrue(boardA.checkForLose());
        assertTrue(boardB.checkForWin(boardA));
    }

    @Test
    public void test_app_doPlacementPhase_calls_both_players() throws IOException {
        V1ShipFactory f = new V1ShipFactory();
        BattleShipBoard<Character> b1 = new BattleShipBoard<>(5, 5, 'X');
        BattleShipBoard<Character> b2 = new BattleShipBoard<>(5, 5, 'X');

        final int[] called = new int[2];

        TextPlayer p1 = new TextPlayer(b1, new BufferedReader(new StringReader("")),
                new PrintStream(new ByteArrayOutputStream()), "A", f) {
            @Override
            public void doPlacementPhase() throws IOException {
                called[0]++;
            }
        };

        TextPlayer p2 = new TextPlayer(b2, new BufferedReader(new StringReader("")),
                new PrintStream(new ByteArrayOutputStream()), "B", f) {
            @Override
            public void doPlacementPhase() throws IOException {
                called[1]++;
            }
        };

        App app = new App(p1, p2);
        app.doPlacementPhase();

        assertEquals(1, called[0]);
        assertEquals(1, called[1]);
    }

    @Test
    public void test_doAttackPhaseV2_A_wins() throws IOException {
        V2ShipFactory f = new V2ShipFactory();

        BattleShipBoard<Character> boardA = new BattleShipBoard<>(5, 5, 'X');
        BattleShipBoard<Character> boardB = new BattleShipBoard<>(5, 5, 'X');

        Ship<Character> s = f.makeSubmarine(new Placement("A0H"));
        addAndSink(boardB, s);

        ByteArrayOutputStream outABytes = new ByteArrayOutputStream();
        PrintStream outA = new PrintStream(outABytes);

        TextPlayer p1 = new TextPlayer(
                boardA,
                new BufferedReader(new StringReader("F\nA0\n")),
                outA,
                "A",
                f);

        TextPlayer p2 = new TextPlayer(
                boardB,
                new BufferedReader(new StringReader("F\nA0\n")),
                new PrintStream(new ByteArrayOutputStream()),
                "B",
                f);

        App app = new App(p1, p2);
        app.doAttackPhaseV2();

        assertTrue(boardB.checkForLose());
        assertTrue(outABytes.toString().contains("PLAYER A WINS"));
    }

    @Test
    public void test_doAttackPhaseV2_B_wins() throws IOException {
        V2ShipFactory f = new V2ShipFactory();

        BattleShipBoard<Character> boardA = new BattleShipBoard<>(5, 5, 'X');
        BattleShipBoard<Character> boardB = new BattleShipBoard<>(5, 5, 'X');

        assertNull(boardA.tryAddShip(f.makeSubmarine(new Placement("A0H"))));
        boardA.fireAt(new Coordinate("A0"));

        assertNull(boardB.tryAddShip(f.makeSubmarine(new Placement("C0H"))));

        ByteArrayOutputStream outBBytes = new ByteArrayOutputStream();
        PrintStream outB = new PrintStream(outBBytes);

        TextPlayer p1 = new TextPlayer(
                boardA,
                new BufferedReader(new StringReader("F\nE4\n")),
                new PrintStream(new ByteArrayOutputStream()),
                "A",
                f);

        TextPlayer p2 = new TextPlayer(
                boardB,
                new BufferedReader(new StringReader("F\nA1\n")),
                outB,
                "B",
                f);

        App app = new App(p1, p2);
        app.doAttackPhaseV2();

        assertTrue(boardA.checkForLose());
        assertTrue(outBBytes.toString().contains("PLAYER B WINS"));
    }

    private BufferedReader br(String s) {
        return new BufferedReader(new StringReader(s));
    }

    @Test
    public void test_createPlayer_human_returns_TextPlayer() throws IOException {
        Board<Character> b = new BattleShipBoard<>(10, 20, 'X');
        AbstractShipFactory<Character> f = new V2ShipFactory();
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(bytes);

        Player p = App.createPlayer("A", b, br("h\n"), out, f, 10, 20);

        assertTrue(p instanceof TextPlayer);
        assertEquals("A", p.getName());
        assertSame(b, p.getBoard());
    }

    @Test
    public void test_createPlayer_computer_returns_ComputerPlayer() throws IOException {
        Board<Character> b = new BattleShipBoard<>(10, 20, 'X');
        AbstractShipFactory<Character> f = new V2ShipFactory();
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(bytes);

        Player p = App.createPlayer("B", b, br("c\n"), out, f, 10, 20);

        assertTrue(p instanceof ComputerPlayer);
        assertEquals("B", p.getName());
        assertSame(b, p.getBoard());
    }

    @Test
    public void test_createPlayer_reprompts_on_invalid_then_accepts() throws IOException {
        Board<Character> b = new BattleShipBoard<>(10, 20, 'X');
        AbstractShipFactory<Character> f = new V2ShipFactory();
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(bytes);

        Player p = App.createPlayer("A", b, br("wat\nh\n"), out, f, 10, 20);

        assertTrue(p instanceof TextPlayer);
        String s = bytes.toString();
        assertTrue(s.contains("Is Player A a human or computer? (h/c)"));
        assertTrue(s.contains("Please enter 'h' or 'c'"));
    }

    @Test
    public void test_createPlayer_throws_on_eof() throws IOException {
        Board<Character> b = new BattleShipBoard<>(10, 20, 'X');
        AbstractShipFactory<Character> f = new V2ShipFactory();
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(bytes);

        assertThrows(IOException.class, () -> {
            App.createPlayer("A", b, br(""), out, f, 10, 20);
        });
    }

    @Test
    public void test_createPlayer_empty_line_then_human() throws IOException {
        Board<Character> b = new BattleShipBoard<>(10, 20, 'X');
        AbstractShipFactory<Character> f = new V2ShipFactory();
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(bytes);

        Player p = App.createPlayer("A", b, br("\n h \n"), out, f, 10, 20);

        assertTrue(p instanceof TextPlayer);
        String s = bytes.toString();
        assertTrue(s.contains("Please enter 'h' or 'c'"));
    }

}
